



interface ImageOperations  {
    // operations for single image
    
    // operations for multiple images
    void ImageOperations();
    void createImages(DOMString base46Str);
    void grayscale_avgs();
    void grayscale_lums();
    void colorMasks(float r, float g, float b);
    void encodeMessages(DOMString  message);
    DOMString encodeBytes();
    void std_convolve_clamp_to_0(octet channel, unsigned long ker_w, unsigned long ker_h, unsigned long cr, unsigned long cc);
    void std_convolve_clamp_to_border(octet channel, unsigned long ker_w, unsigned long ker_h, unsigned long cr, unsigned long cc);
    void Undos();
};